### ISSUE TITLE
error running on 3.21.1 distribution

### ISSUE THREAD

**Issue by bsorrentino** [sonatype-nexus-community/nexus-blobstore-azure-cloud#9]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Install bundle on 3.21.1 distribution

* **What feature or behavior is this required for?**
need support of Azure Blob Storage

* **How could we solve this issue? (Not knowing is okay!)**
the exception is

```
2020-02-22 17:24:26,051+0000 ERROR [qtp492469808-50]  admin org.sonatype.nexus.extdirect.internal.ExtDirectExceptionHandler - Failed to invoke action method:
 coreui_Blobstore.create, java-method: org.sonatype.nexus.coreui.BlobStoreComponent.create
java.lang.IncompatibleClassChangeError: Found interface org.sonatype.nexus.blobstore.api.BlobStoreConfiguration, but class was expected
        at org.sonatype.nexus.blobstore.azure.internal.AzureStorageClientFactory.create(AzureStorageClientFactory.java:46)
        at org.sonatype.nexus.blobstore.azure.internal.AzureBlobStore.doInit(AzureBlobStore.java:387)
        at org.sonatype.nexus.blobstore.BlobStoreSupport.init(BlobStoreSupport.java:243)
        at org.sonatype.nexus.repository.internal.blobstore.BlobStoreManagerImpl.create(BlobStoreManagerImpl.java:196)
        at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
        at org.sonatype.nexus.common.stateguard.StateGuard$GuardImpl.run(StateGuard.java:272)
        at org.sonatype.nexus.common.stateguard.GuardedInterceptor.invoke(GuardedInterceptor.java:53)
        at org.sonatype.nexus.blobstore.api.BlobStoreManager$create$3.call(Unknown Source)
        at org.sonatype.nexus.coreui.BlobStoreComponent.create(BlobStoreComponent.groovy:166)

        at com.palominolabs.metrics.guice.ExceptionMeteredInterceptor.invoke(ExceptionMeteredInterceptor.java:23)
        at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:26)
        at org.sonatype.nexus.validation.internal.ValidationInterceptor.invoke(ValidationInterceptor.java:53)
        at org.apache.shiro.guice.aop.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:49)
        at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68)
        at org.apache.shiro.guice.aop.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.invokeJavaMethod(DispatcherBase.java:142)
        at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.invokeMethod(DispatcherBase.java:133)
        at org.sonatype.nexus.extdirect.internal.ExtDirectDispatcher.invokeMethod(ExtDirectDispatcher.java:82)
        at com.softwarementors.extjs.djn.router.dispatcher.DispatcherBase.dispatch(DispatcherBase.java:63)
        at com.softwarementors.extjs.djn.router.processor.standard.StandardRequestProcessorBase.dispatchStandardMethod(StandardRequestProcessorBase.java:73)
        at com.softwarementors.extjs.djn.router.processor.standard.json.JsonRequestProcessor.processIndividualRequest(JsonRequestProcessor.java:502)
        at com.softwarementors.extjs.djn.router.processor.standard.json.JsonRequestProcessor.processIndividualRequestsInThisThread(JsonRequestProcessor.java:
150)
        at com.softwarementors.extjs.djn.router.processor.standard.json.JsonRequestProcessor.process(JsonRequestProcessor.java:133)
Linter
.....

```
* **Anything else?**

Seems to me that `BlobStoreConfiguration` was a class and currently is an interface

**Comment by mattjohnson** [comment]
Hi, thanks for report! The current version of this plugin is built against 3.19.1-01. I'll work on getting it updated to the latest release, which does appear to have some API changes.

**Comment by mattjohnson** [comment]
I've pushed an update that should resolve the issue. Please confirm it works and I'll close the issue. Thanks!

**Comment by bsorrentino** [comment]
It works 

Thank you
